- app/assets/stylesheets/application.css
deleted require on Jquery fancybox on css application file
> deleted require on Jquery fancybox on css application file

- app/models/user.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- config/environments/development.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20210311173412_devise_create_users.rb
- db/schema.rb
- spec/models/user_spec.rb
> devise added

- config/application.rb
- config/locales/devise.fr.yml
updated all devise messages in french
> updated all devise messages in french

- app/models/category.rb
- app/models/language.rb
- app/models/language_media.rb
- app/models/media.rb
- app/models/project.rb
- app/models/project_category.rb
- app/models/project_language.rb
- app/models/project_media.rb
- db/migrate/20210313205129_create_collaborations.rb
- db/migrate/20210313213652_create_donations.rb
- db/migrate/20210314011647_create_media.rb
- db/migrate/20210314011916_create_project_media.rb
- db/migrate/20210314013723_create_categories.rb
- db/migrate/20210314013813_create_project_categories.rb
- db/migrate/20210314014643_create_languages.rb
- db/migrate/20210314014845_create_project_languages.rb
- db/migrate/20210314023302_create_language_media.rb
- db/schema.rb
- db/seeds.rb
- spec/models/category_spec.rb
- spec/models/language_medium_spec.rb
- spec/models/language_spec.rb
- spec/models/medium_spec.rb
- spec/models/project_category_spec.rb
- spec/models/project_language_spec.rb
- spec/models/project_medium_spec.rb
added Media ProjectMedia Category ProjectCategory LanguageMedia Language ProjectLanguage models and relations
> added Media ProjectMedia Category ProjectCategory LanguageMedia Language ProjectLanguage models and relations

- app/models/badge.rb
- app/models/badge_media.rb
- app/models/badge_type.rb
- app/models/category.rb
- app/models/collaboration.rb
- app/models/comment.rb
- app/models/comment_answer.rb
- app/models/comment_answer_upvote.rb
- app/models/comment_upvote.rb
- app/models/competition.rb
- app/models/donation.rb
- app/models/language.rb
- app/models/language_media.rb
- app/models/media.rb
- app/models/media_type.rb
- app/models/project.rb
- app/models/project_category.rb
- app/models/project_competition.rb
- app/models/project_competition_upvote.rb
- app/models/project_language.rb
- app/models/project_media.rb
- app/models/role.rb
added validations on each model
> added validations on each model

- db/migrate/20210316054215_add_default_on_projects_table.rb
- db/migrate/20210316055607_add_default_on_projects_table_on_is_validated_column.rb
- db/schema.rb
added default value (false)  on is_validated & is_completed on projects table
> added default value (false)  on is_validated & is_completed on projects table

- Gemfile
- Gemfile.lock
- app/assets/javascripts/callbacks.coffee
- app/assets/stylesheets/callbacks.scss
- app/controllers/callbacks_controller.rb
- app/helpers/callbacks_helper.rb
- app/models/user.rb
- app/views/devise/sessions/new.html.erb
- config/initializers/devise.rb
- config/routes.rb
- db/migrate/20210316063213_add_columns_to_users.rb
- db/schema.rb
- spec/helpers/callbacks_helper_spec.rb
- spec/requests/callbacks_spec.rb
> Github omniauth sign_in done

- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
update text errors on edit project
> update text errors on edit project

- config/locales/devise.en.yml
- config/locales/devise.fr.yml
updated devise translations routes for production
> updated devise translations routes for production

- app/controllers/application_controller.rb
- config/locales/devise.en.yml
- config/locales/devise.fr.yml
- config/locales/routes.yml
- config/routes.rb
updated devise translations routes in routes.yml and add around_action callback for set local from url in application controller
> updated devise translations routes in routes.yml and add around_action callback for set local from url

- app/views/projects/index.html.erb
> changed to 2 indentation

- Gemfile
- Gemfile.lock
- config/environments/development.rb
> bullet configuration done

- db/migrate/20210319133058_add_column_is_admin_to_users.rb
- db/schema.rb
added default value to is_admin on user table
> added default value to is_admin on user table

- app/views/categories/index.html.erb
- app/views/layouts/_footer.html.erb
- app/views/layouts/application.html.erb
> footer done

- Gemfile
- Gemfile.lock
- app/mailers/application_mailer.rb
- app/mailers/user_mailer.rb
- app/models/user.rb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/user_mailer/welcome_email.html.erb
- app/views/user_mailer/welcome_email.text.erb
- config/environment.rb
- config/environments/development.rb
- config/environments/production.rb
- config/initializers/devise.rb
- spec/mailers/previews/user_mailer_preview.rb
- spec/mailers/user_mailer_spec.rb
> welcome_mailer done

- config/environment.rb
Mailer configuration updated with mailjet
> Mailer configuration updated with mailjet

- app/views/devise/passwords/edit.html.erb
updated edit password devise view
> updated edit password devise view

- app/views/devise/sessions/new.html.erb
updated new session devise view with link for redirect to edit password path
> updated new session devise view with link for redirect to edit password path

- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/devise/registrations/edit.html.erb
- app/views/users/show.html.erb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20210321073200_create_active_storage_tables.active_storage.rb
- db/schema.rb
> Active storage

- config/environments/production.rb
- config/storage.yml
added aws s3 configuration for production
> added aws s3 configuration for production

- Gemfile.lock
> updated Gemfile.lock

- app/controllers/categories_controller.rb
- app/models/project.rb
- app/views/categories/show.html.erb
- db/seeds.rb
updated request on categories controllers and project model
> updated request on categories controllers and project model

- app/controllers/languages_controller.rb
- app/models/language.rb
- db/migrate/20210323053905_add_slug_to_languages.rb
- db/schema.rb
> added slug on Languages

- app/models/language.rb
- app/views/categories/index.html.erb
updated language model with slug verification in case how name changed
> updated language model with slug verification in case how name changed

- app/views/languages/index.html.erb
> languages index done

- app/views/layouts/_footer.html.erb
added index languages into footer
> added index languages into footer

- app/views/languages/show.html.erb
correction of h1 on show language
> correction of h1 on show language

- app/views/projects/show.html.erb
updated animation on upvote button in project show
> updated animation on upvote button in project show

- app/views/languages/index.html.erb
updated animation on languages index
> updated animation on languages index

- app/assets/javascripts/admins/donations.coffee
- app/assets/javascripts/admins/projects.coffee
- app/assets/javascripts/admins/users.coffee
- app/assets/stylesheets/admins/donations.scss
- app/assets/stylesheets/admins/projects.scss
- app/assets/stylesheets/admins/users.scss
- app/controllers/admin/donations_controller.rb
- app/controllers/admin/projects_controller.rb
- app/controllers/admin/users_controller.rb
- app/controllers/admin_controller.rb
- app/helpers/admins/donations_helper.rb
- app/helpers/admins/projects_helper.rb
- app/helpers/admins/users_helper.rb
- app/views/admin/donations/index.html.erb
- app/views/admin/index.html.erb
- app/views/admin/projects/index.html.erb
- app/views/admin/users/destroy.js.erb
- app/views/admin/users/edit.html.erb
- app/views/admin/users/index.html.erb
- app/views/layouts/_navbar.html.erb
- config/routes.rb
- spec/helpers/admins/donations_helper_spec.rb
- spec/helpers/admins/projects_helper_spec.rb
- spec/helpers/admins/users_helper_spec.rb
- spec/requests/admins/donations_spec.rb
- spec/requests/admins/projects_spec.rb
- spec/requests/admins/users_spec.rb
Users gestion by admin in admin namespace done
> Users gestion by admin in admin namespace done

- app/controllers/comments_controller.rb
- app/controllers/projects_controller.rb
- app/views/comments/_comment.html.erb
- app/views/comments/_form.html.erb
- app/views/comments/create.js.erb
- app/views/projects/show.html.erb
reset form after ajax submission on show project
> Project page

- app/controllers/projects_controller.rb
- app/views/projects/show.html.erb
- app/views/users/show.html.erb
updated project show spacing on elements
> updated project show spacing on elements

- app/views/users/show.html.erb
Added empty image if number of collaboration on user show are nil
> Added empty image if number of collaboration on user show are nil

- app/views/users/show.html.erb
change text on bottom on svg if current_user == @user
> change text on bottom on svg if current_user == @user

- Gemfile.lock
- app/controllers/projects_controller.rb
- app/models/project.rb
- app/models/project_upvote.rb
- app/views/projects/index.html.erb
- db/migrate/20210327071632_add_column_counter_cache_to_projects.rb
- db/migrate/20210327072532_populate_project_upvotes_count.rb
- db/schema.rb
- db/seeds.rb
- lib/tasks/counters.rake
> Homepage done
